### PR TITLE
Implement SciPipe example workflow

### PR DESCRIPTION
**Pull request by samuell**
This PR implements an example workflow in [SciPipe](https://scipipe.org/).

As not being an expert in RNA-Seq, I haven't been able to double-check the results, but the workflow completes successfully and is modeled closely after the Nextflow example.

### CODE REVIEW

**Review by pditommaso — COMMENTED** [review]
Just a suggestion more than a requirement, what about adding a GitHub action to run it. Other than testing it's useful to show to install and run it

**Comment by samuell** [comment]
> Just a suggestion more than a requirement, what about adding a GitHub action to run it. Other than testing it's useful to show to install and run it

Good point! Just saw about the GH workflow defs yesterday. Will make a try! :+1:

**Comment by samuell** [comment]
> > Just a suggestion more than a requirement, what about adding a GitHub action to run it. Other than testing it's useful to show to install and run it
> 
> Thanks Paolo, good point! Just saw about the GH workflow defs yesterday. Will make a try!

Done.

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
Thanks! Leave to @jonathangoeke to merge this.

**Review by jonathangoeke — APPROVED** [review]
Thanks for this submission @samuell! I have tested the workflow, it's easy to follow and returns the expected results. Thanks for the review @pditommaso! I will merge this in the next days

**Pull request merged**
